import { useState } from "react";
import { toast } from "sonner";
import { ApiError } from "@/lib/api";
import { useAdjustStockMutation } from "@/lib/queries";
import { INPUT_CLS, Modal, ModalActions } from "./Modal";

/**
 * AdjustStockModal — Phase 4 M5 Task 4 plan requirement.
 *
 * Manual stock adjustment on a (sku, warehouse) pair. Wraps
 * `useAdjustStockMutation` → POST /api/operation/warehouse/adjust →
 * `operation_adjust_stock(p_sku, p_warehouse_id, p_delta, p_reason)` RPC
 * (migration 0019). The RPC writes a stock_movements row (kind='adjust') and
 * an audit_log entry; the hook invalidates warehouse + movements + dashboard
 * caches on success (queries.ts:1525-1532).
 *
 * Note: this dialog has no proto counterpart — the proto's warehouse screen is
 * read-only (movements are auto-generated by deliver / receive flows). The
 * current stock workflow and the shipped RPC require manual
 * adjust + reason for damage / loss / one-off corrections, so the dialog is
 * proto-style (matches Modal primitive + tone) but content is plan-driven.
 *
 * Validation (mirrors `adjustStockInput` zod, schemas/operation.ts:58-63):
 *   - sku: read-only (prefilled by parent — display only)
 *   - warehouseId: read-only (prefilled by parent)
 *   - delta: signed int, MUST be ≠ 0 (zero is a no-op the server rejects too)
 *   - reason: required, min 1 char (we use min 4 for a meaningful audit trail
 *     since the audit log surfaces this verbatim — server still accepts ≥1)
 *
 * Server-side errors that surface back as toasts:
 *   - P0001 negative_stock — delta would dip qty below 0
 *   - P0001 below_reserved — delta would dip qty below stock_balances.reserved
 */
interface Props {
  /** Pre-filled SKU code; the modal does not allow editing this. */
  sku: string;
  /** Pre-filled warehouse UUID; not editable. */
  warehouseId: string;
  /** Display label for the warehouse (proto-style "{name}"). */
  warehouseName: string;
  /** Current qty in this (sku, warehouse) for the read-only header preview. */
  currentQty: number;
  /** Reserved qty — used to surface the "below_reserved" pre-empt warning
   *  inline before the user submits a delta that would clearly fail server-side. */
  reservedQty: number;
  /** Optional friendlier display name for the SKU (e.g. "Carres Cloud · King"). */
  skuLabel?: string;
  onClose: () => void;
}

export default function AdjustStockModal({
  sku,
  warehouseId,
  warehouseName,
  currentQty,
  reservedQty,
  skuLabel,
  onClose,
}: Props) {
  const [deltaText, setDeltaText] = useState("");
  const [reason, setReason] = useState("");
  const adjust = useAdjustStockMutation();

  // Parse delta: empty or non-numeric → null (invalid). The input is type=number
  // so the browser already filters most non-digits, but a `-` alone or `+` alone
  // both yield NaN here so we coerce to null.
  const delta = (() => {
    const t = deltaText.trim();
    if (!t) return null;
    const n = Number(t);
    if (!Number.isFinite(n) || !Number.isInteger(n)) return null;
    return n;
  })();
  const reasonTrim = reason.trim();
  const projected = delta !== null ? currentQty + delta : currentQty;
  const wouldGoNegative = delta !== null && projected < 0;
  const wouldGoBelowReserved = delta !== null && projected < reservedQty;

  const valid =
    delta !== null &&
    delta !== 0 &&
    reasonTrim.length >= 1 &&
    !wouldGoNegative &&
    !wouldGoBelowReserved &&
    !adjust.isPending;

  async function submit() {
    if (!valid || delta === null) return;
    try {
      await adjust.mutateAsync({
        sku,
        warehouseId,
        delta,
        reason: reasonTrim,
      });
      const sign = delta > 0 ? "+" : "";
      toast.success(
        `${sku} · ${warehouseName} · ${sign}${delta} unit${Math.abs(delta) === 1 ? "" : "s"} adjusted`,
      );
      onClose();
    } catch (e: unknown) {
      if (e instanceof ApiError) toast.error(e.message || "Adjust failed");
      else toast.error(e instanceof Error ? e.message : "Adjust failed");
    }
  }

  return (
    <Modal title={`Adjust stock · ${sku}`} onClose={onClose}>
      <div className="text-meta text-base-600 mb-3.5 font-body">
        Manually correct stock at <strong>{warehouseName}</strong>. Use a
        positive number for ad-hoc inbound (e.g. transfer-in, found goods) and
        a negative number for damage / loss / shrinkage. Every adjustment
        writes to the movement log + audit trail.
      </div>

      <div
        className="card mb-3.5 px-3.5 py-2.5"
        style={{ background: "var(--base-50)" }}
        data-testid="adjust-stock-context"
      >
        <div className="label mb-1.5">Adjusting</div>
        <div className="text-meta font-body">
          <strong>{skuLabel ?? sku}</strong>
          {skuLabel ? (
            <span className="font-mono text-label text-base-500 ml-1.5">{sku}</span>
          ) : null}
        </div>
        <div className="text-meta font-body mt-0.5">
          at <strong>{warehouseName}</strong>
        </div>
        <div className="font-mono text-label text-base-500 mt-1.5">
          Current {currentQty} · reserved {reservedQty} · available{" "}
          {Math.max(0, currentQty - reservedQty)}
        </div>
      </div>

      <div className="mb-3.5">
        <label className="label mb-1.5 block" htmlFor="adjust-delta">
          Delta (signed) *
        </label>
        <input
          id="adjust-delta"
          type="number"
          step="1"
          inputMode="numeric"
          placeholder="e.g. -2 for damage · +5 for transfer-in"
          value={deltaText}
          onChange={(e) => setDeltaText(e.target.value)}
          className={INPUT_CLS}
          data-testid="adjust-delta-input"
        />
        <div className="text-label text-base-500 mt-1 font-body">
          Projected after adjust:{" "}
          <span className="font-mono">
            {delta !== null ? projected : currentQty}
          </span>
          {delta !== null ? (
            <>
              {" "}
              ({delta > 0 ? "+" : ""}
              {delta})
            </>
          ) : null}
        </div>
        {wouldGoNegative ? (
          <div
            className="text-label font-body mt-2 px-2.5 py-1.5 rounded-[4px]"
            style={{
              color: "var(--destructive)",
              background: "var(--error-soft)",
            }}
            data-testid="adjust-warning-negative"
          >
            That adjust would push qty below 0 — not allowed.
          </div>
        ) : wouldGoBelowReserved ? (
          <div
            className="text-label font-body mt-2 px-2.5 py-1.5 rounded-[4px]"
            style={{
              color: "var(--destructive)",
              background: "var(--error-soft)",
            }}
            data-testid="adjust-warning-reserved"
          >
            That adjust would dip below the reserved {reservedQty} (orders
            already promised this stock).
          </div>
        ) : null}
      </div>

      <div className="mb-4">
        <label className="label mb-1.5 block" htmlFor="adjust-reason">
          Reason *
        </label>
        <textarea
          id="adjust-reason"
          rows={3}
          placeholder="e.g. 2 units damaged on receiving · forklift dent · transfer-in from KL3"
          value={reason}
          onChange={(e) => setReason(e.target.value)}
          className={`${INPUT_CLS} resize-y`}
          data-testid="adjust-reason-input"
        />
        <div className="text-label text-base-500 mt-1 font-body">
          Surfaces in the audit log + movement note — keep it brief but
          specific.
        </div>
      </div>

      <ModalActions
        onCancel={onClose}
        onPrimary={submit}
        primary="Apply adjustment"
        primaryDisabled={!valid}
        primaryPending={adjust.isPending}
      />
    </Modal>
  );
}
