// design-standard: not-a-list-page — governed kit PageShell owns this generated report frame.
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useNavigate, useSearchParams } from "react-router-dom";
import { fmtMoney } from "@carres/shared";
import { apiFetch } from "@/lib/api";
import { appTodayIso, fmtMonth } from "@/lib/fmt-date";
import Button from "@/components/kit/Button";
import PageShell from "@/components/kit/PageShell";
import Select from "@/components/kit/Select";

type Party={id:string;name:string}; type Row={issueNo:string;observedOn:string;description:string;actOrOmission:string;incurred:number;recoverable:number;recovered:number};
type Report={party?:Party;month:string;sections:{confirmed:Row[];waiting:Row[];disputed:Row[]};totals:{distinctIssues:number;incurred:number;recoverable:number;recovered:number}};
const MONTH=/^\d{4}-\d{2}$/;
/** The current month and the eleven before it, newest first — plus the URL's month when it is older. */
function monthOptions(today:string,chosen:string){const [y,m]=today.slice(0,7).split("-").map(Number);const months=Array.from({length:12},(_,i)=>{const d=new Date(Date.UTC(y!,m!-1-i,1));return d.toISOString().slice(0,7);});if(!months.includes(chosen))months.push(chosen);return months.map((value)=>({value,label:fmtMonth(value)}));}
export default function IssueRelatedPartyReport(){const navigate=useNavigate(),[search,setSearch]=useSearchParams(),[partyId,setPartyId]=useState<string>();const today=appTodayIso();const asked=search.get("month")??"";const month=MONTH.test(asked)?asked:today.slice(0,7);const setMonth=(value:string)=>setSearch((old)=>{const next=new URLSearchParams(old);next.set("month",value);return next;},{replace:true});const parties=useQuery<{items:Party[]}>({queryKey:["issue-related-parties"],queryFn:()=>apiFetch("/api/ops/issues/related-parties")});const report=useQuery<Report>({queryKey:["issue-party-report",partyId,month],queryFn:()=>apiFetch(`/api/ops/issues/reports/${partyId}?month=${month}`),enabled:Boolean(partyId)});const empty={confirmed:[],waiting:[],disputed:[]};const sections=report.data?.sections??empty;return <PageShell variant="list" title="Monthly report — Related Party" titleRight={<Button onClick={()=>navigate("/operation/issues")}>Back to Issue Tracker</Button>} toolbar={<div className="flex flex-wrap items-end gap-3"><Select id="report-party" label="Related Party" value={partyId} onValueChange={setPartyId} placeholder="Choose Related Party" options={(parties.data?.items??[]).map((p)=>({value:p.id,label:p.name}))}/><Select id="report-month" label="Month" value={month} onValueChange={setMonth} options={monthOptions(today,month)}/></div>} footer={<span>{report.data?.totals.distinctIssues??0} distinct issues · {fmtMonth(month)}</span>}><div className="min-h-0 flex-1 overflow-auto rounded-card border border-kit-slate-5 bg-white p-5"><div className="mb-5 grid grid-cols-3 gap-3"><Money label="Cost incurred" value={report.data?.totals.incurred??0}/><Money label="Amount recoverable" value={report.data?.totals.recoverable??0}/><Money label="Amount recovered" value={report.data?.totals.recovered??0}/></div><ReportSection title="Confirmed fault" rows={sections.confirmed}/><ReportSection title="Waiting response" rows={sections.waiting}/><ReportSection title="Disputed" rows={sections.disputed}/></div></PageShell>}
function Money({label,value}:{label:string;value:number}){return <div className="rounded-card border border-kit-slate-5 p-3"><div className="text-label text-kit-slate-11">{label}</div><div className="mt-1 text-section tabular-nums">{fmtMoney(value)}</div></div>}
function ReportSection({title,rows}:{title:string;rows:Row[]}){return <section className="mb-5"><h2 className="mb-2 text-section">{title}</h2>{rows.length===0?<p className="text-body text-kit-slate-11">No issues in this section.</p>:<table className="w-full text-body"><thead><tr className="border-b border-kit-slate-5 text-left"><th className="p-2">Issue No.</th><th>Fact</th><th>This party</th><th>Money</th></tr></thead><tbody>{rows.map((r)=><tr key={`${title}-${r.issueNo}`} className="border-b border-kit-slate-4"><td className="p-2 font-medium">{r.issueNo}</td><td>{r.description}</td><td>{r.actOrOmission}</td><td className="tabular-nums">{fmtMoney(r.incurred)} · Recover {fmtMoney(r.recoverable)} · Received {fmtMoney(r.recovered)}</td></tr>)}</tbody></table>}</section>}
