// design-standard: not-a-list-page — governed kit PageShell owns this workspace's list frame.
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiFetch } from "@/lib/api";
import Button from "@/components/kit/Button";
import Input from "@/components/kit/Input";
import Modal from "@/components/kit/Modal";
import PageShell from "@/components/kit/PageShell";
import StatusPill from "@/components/kit/StatusPill";

type IssueRow = { id: string; issue_no: string; observed_on: string; official_english: string; status: string; current_action_owner_name?: string; current_action_do?: string; current_action_recipient?: string; current_action_result?: string; current_action_due_on?: string; issue_links: Array<{ object_label: string }>; issue_fault_owners: Array<{ owner_name: string }>; issue_money_links: Array<{ track: string; amount: number }> };
type Choice = { value: string; label: string };
const OBJECTS: Choice[] = [{ value: "item", label: "Item" }, { value: "delivery", label: "Delivery" }, { value: "document", label: "Document" }, { value: "payment", label: "Payment" }, { value: "customer_information", label: "Customer information" }, { value: "staff_work", label: "Staff work" }, { value: "other", label: "Something else" }];
const PROBLEMS: Choice[] = [{ value: "wrong_item", label: "Wrong item" }, { value: "damaged", label: "Damaged" }, { value: "missing", label: "Missing" }, { value: "wrong_quantity", label: "Wrong quantity" }, { value: "late", label: "Late" }, { value: "no_reply", label: "No reply" }, { value: "wrong_information", label: "Wrong information" }, { value: "work_not_done", label: "Required work was not done" }, { value: "not_sure", label: "I am not sure" }];
const VIEWS: Choice[] = [{ value: "all", label: "All Issues" }, { value: "needs_triage", label: "Needs triage" }, { value: "wednesday", label: "Wednesday review" }, { value: "internal", label: "Internal issues" }, { value: "waiting_response", label: "Waiting staff response" }, { value: "waiting_review", label: "Waiting reviewer finding" }, { value: "closed", label: "Closed" }, { value: "voided", label: "Voided" }];

export default function OperationIssueTracker() {
  const navigate = useNavigate();
  const [view, setView] = useState("all"), [open, setOpen] = useState(false), [selected, setSelected] = useState<IssueRow | null>(null);
  const list = useQuery<{ items: IssueRow[]; total: number }>({ queryKey: ["issues", view], queryFn: () => apiFetch(`/api/ops/issues?view=${view}`) });
  return <PageShell variant="list" title="Issue Tracker" titleRight={<div className="flex gap-2"><Button onClick={() => navigate("/operation/issues/reports")}>Monthly report</Button><Button variant="primary" onClick={() => setOpen(true)}>Record issue</Button></div>}
    facet={<nav aria-label="Issue views" className="flex flex-col gap-1">{VIEWS.map((item) => <Button key={item.value} variant={view === item.value ? "neutral" : "ghost"} onClick={() => setView(item.value)}>{item.label}</Button>)}</nav>} facetOpen onFacetToggle={() => {}}
    toolbar={<span className="text-body text-kit-slate-11">Every issue stays for facts, money and learning.</span>}
    footer={<span>{list.data?.total ?? 0} issues</span>}>
    <div className="min-h-0 flex-1 overflow-auto rounded-card border border-kit-slate-5 bg-white">
      <table className="w-full border-collapse text-body"><thead className="sticky top-0 bg-kit-slate-3 text-left text-label text-kit-slate-11"><tr>{["Issue No.","Observed","Issue","Linked object","Fault Owners","Current Action","Money","Review state"].map((h) => <th key={h} className="h-10 border-b border-kit-slate-5 px-3 font-medium">{h}</th>)}</tr></thead>
      <tbody>{(list.data?.items ?? []).map((row) => { const incurred = row.issue_money_links.filter((m) => m.track === "incurred").reduce((s,m) => s + Number(m.amount),0); return <tr key={row.id} className="h-[38px] cursor-pointer border-b border-kit-slate-4 hover:bg-kit-slate-3" onClick={() => setSelected(row)}><td className="px-3 font-medium text-kit-blue-11">{row.issue_no}</td><td className="px-3 whitespace-nowrap">{row.observed_on}</td><td className="max-w-72 px-3"><span className="line-clamp-2">{row.official_english}</span></td><td className="px-3">{row.issue_links.map((x) => x.object_label).join(", ") || "—"}</td><td className="px-3">{row.issue_fault_owners.map((x) => x.owner_name).join(", ") || "Waiting review"}</td><td className="max-w-72 px-3">{row.current_action_do ? `${row.current_action_owner_name} · ${row.current_action_do} · ${row.current_action_recipient} · Need ${row.current_action_result} · ${row.current_action_due_on}` : "Set next action"}</td><td className="px-3 whitespace-nowrap">{incurred ? `RM${incurred.toFixed(2)} incurred` : "No cost recorded"}</td><td className="px-3"><StatusPill tone={row.status === "closed" ? "success" : row.status.includes("waiting") ? "warning" : "info"}>{row.status.replaceAll("_", " ")}</StatusPill></td></tr>; })}</tbody></table>
    </div>
    <RecordIssueModal open={open} onOpenChange={setOpen} />
    <IssueWorkspace row={selected} onClose={() => setSelected(null)} />
  </PageShell>;
}

function ChoiceGrid({ choices, selected, onChoose }: { choices: Choice[]; selected?: string; onChoose: (value: string) => void }) { return <div className="grid grid-cols-2 gap-2">{choices.map((choice) => <Button key={choice.value} variant={selected === choice.value ? "primary" : "neutral"} onClick={() => onChoose(choice.value)}>{choice.label}</Button>)}</div>; }

function RecordIssueModal({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const qc = useQueryClient(); const [step, setStep] = useState(0); const [form, setForm] = useState<Record<string,string>>({});
  const save = useMutation({ mutationFn: () => apiFetch("/api/ops/issues", { method: "POST", body: JSON.stringify({ intake: { problemObject: form.object, observedProblem: form.problem, foundByKind: form.foundByKind || "me", foundByName: form.foundByName, observedOn: form.observedOn, linkedObjects: [{ kind: form.linkKind || "issue", id: form.linkId, label: form.linkLabel }], affectedObject: form.affectedObject, impact: form.impact, evidence: [{ kind: form.evidence, count: 1 }] }, sourceModule: form.linkKind || "other", materiality: "routine", work: { owner: form.owner, object: "New issue", recipient: form.recipient, action: form.action, requiredResult: form.result, dueOn: form.dueOn } }) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["issues"] }); onOpenChange(false); setStep(0); setForm({}); } });
  const set = (key: string, value: string) => setForm((old) => ({ ...old, [key]: value }));
  const pages = [
    <section key="object"><h3 className="mb-3 text-section">What has a problem?</h3><ChoiceGrid choices={OBJECTS} selected={form.object} onChoose={(v) => { set("object",v); setStep(1); }} /></section>,
    <section key="problem"><h3 className="mb-3 text-section">What did you see?</h3><ChoiceGrid choices={PROBLEMS} selected={form.problem} onChoose={(v) => { set("problem",v); setStep(2); }} /></section>,
    <section key="fact" className="grid gap-3"><h3 className="text-section">Tell us the exact facts</h3><Input id="foundByName" label="Who found it?" value={form.foundByName ?? ""} onChange={(e) => set("foundByName",e.target.value)} /><Input id="observedOn" label="When did you see it? YYYY-MM-DD" value={form.observedOn ?? ""} onChange={(e) => set("observedOn",e.target.value)} /><Input id="affectedObject" label="Which item, delivery, document or staff work?" value={form.affectedObject ?? ""} onChange={(e) => set("affectedObject",e.target.value)} /><Input id="linkLabel" label="Linked number, for example SO-1319" value={form.linkLabel ?? ""} onChange={(e) => { set("linkLabel",e.target.value); set("linkId",e.target.value); }} /><h4 className="text-label">What cannot continue?</h4><ChoiceGrid choices={[{value:"Customer work cannot continue",label:"Customer work"},{value:"Delivery cannot continue",label:"Delivery"},{value:"Warehouse work cannot continue",label:"Warehouse work"},{value:"Finance work cannot continue",label:"Finance work"},{value:"No work was stopped",label:"Nothing stopped"}]} selected={form.impact} onChoose={(v)=>set("impact",v)} /></section>,
    <section key="evidence"><h3 className="mb-3 text-section">What proof do you have?</h3><ChoiceGrid choices={[{value:"photo",label:"Photo"},{value:"video",label:"Video"},{value:"whatsapp_reply",label:"WhatsApp reply"},{value:"delivery_document",label:"Delivery document"},{value:"other_document",label:"Other document"}]} selected={form.evidence} onChoose={(v)=>{set("evidence",v);setStep(4)}} /></section>,
    <section key="action" className="grid gap-3"><h3 className="text-section">What must happen next?</h3><Input id="owner" label="Who must do it?" value={form.owner ?? ""} onChange={(e) => set("owner",e.target.value)} /><h4 className="text-label">What must they do?</h4><ChoiceGrid choices={[{value:"Send the issue proof and ask for acceptance",label:"Send proof and ask"},{value:"Call about the issue and ask for an answer",label:"Call and ask"},{value:"Check the linked record and add the missing proof",label:"Check record and add proof"},{value:"Correct the item or document and get confirmation",label:"Correct and confirm"}]} selected={form.action} onChoose={(v)=>set("action",v)} /><Input id="recipient" label="Who must receive it?" value={form.recipient ?? ""} onChange={(e) => set("recipient",e.target.value)} /><h4 className="text-label">What result is needed?</h4><ChoiceGrid choices={[{value:"Acceptance or rejection is recorded",label:"Acceptance or rejection"},{value:"Repair or replacement is confirmed",label:"Repair or replacement"},{value:"The missing proof is added",label:"Missing proof added"},{value:"The corrected fact is confirmed",label:"Correction confirmed"}]} selected={form.result} onChoose={(v)=>set("result",v)} /><Input id="dueOn" label="When must it be ready? YYYY-MM-DD" value={form.dueOn ?? ""} onChange={(e) => set("dueOn",e.target.value)} /></section>,
  ];
  const canNext = (step !== 2 || ["foundByName","observedOn","affectedObject","linkLabel","impact"].every((k) => form[k])) && (step !== 3 || Boolean(form.evidence));
  return <Modal open={open} onOpenChange={onOpenChange} title="Record issue" description="Choose facts. The system writes the official English." footer={<div className="flex justify-between gap-2">{step > 0 && <Button variant="ghost" onClick={() => setStep((s) => s-1)}>Back</Button>}{step < pages.length-1 ? <Button variant="primary" disabled={!canNext} onClick={() => setStep((s) => s+1)}>Next</Button> : <Button variant="primary" loading={save.isPending} onClick={() => save.mutate()}>Record issue</Button>}</div>}>{pages[step]}</Modal>;
}

function IssueWorkspace({ row, onClose }: { row: IssueRow | null; onClose: () => void }) { return <Modal open={Boolean(row)} onOpenChange={(value) => !value && onClose()} title={row?.issue_no ?? "Issue"} width="wide" footer={<Button variant="neutral" onClick={onClose}>Close</Button>}><div className="grid gap-4"><section><h3 className="text-section">What is true</h3><p className="mt-1 text-body">{row?.official_english}</p></section><section className="rounded-card border border-kit-blue-5 bg-kit-blue-2 p-4"><h3 className="text-section">Current Action</h3><p className="mt-1 text-body">{row?.current_action_owner_name ?? "Set an owner"} · {row?.current_action_do ?? "Set the exact action"} · Contact {row?.current_action_recipient ?? "the receiving party"} · Need {row?.current_action_result ?? "the required result"} · {row?.current_action_due_on ?? "set a date"}</p></section><div className="grid grid-cols-3 gap-3"><section><h3 className="text-section">Fault Owners</h3><p>{row?.issue_fault_owners.map((x) => x.owner_name).join(", ") || "Waiting reviewer finding"}</p></section><section><h3 className="text-section">Money</h3><p>Cost incurred · Amount recoverable · Amount recovered</p></section><section><h3 className="text-section">Wednesday review</h3><p>Fact · responsibility · action · result · learning</p></section></div></div></Modal>; }
