-- =============================================================================
-- 0076_purchase_order_lines_multi_variant_pk.sql
-- =============================================================================
-- Multi-variant PO lines (Loo 2026-05-10): same SKU with different bedframe
-- color/gap MUST coexist in the same PO. Previous PK (po_id, sku) prevented
-- this — issue surfaced when auto-fill from shortage aggregated 3 dealer
-- orders all wanting BF-001 in different colors and crashed on insert with
-- 23505 unique_violation.
--
-- Decision (Loo 2026-05-10): bedframe = "no need to split, all colors in one
-- PO" (operator picks). Sofa = "split per fabric, one PO per item" (HoOKkA
-- requirement). The schema must support BOTH layouts — the operator chooses
-- per-supplier at PO creation time, the schema can't pre-decide.
--
-- This migration:
--   1. ALTER purchase_order_lines: drop old PK (po_id, sku), add `id uuid`
--      generated by gen_random_uuid() as the new PK. Add unique index on
--      (po_id, sku, coalesce(attrs::text, '')) to prevent true duplicates
--      (same po + sku + attrs combo) without blocking different-attrs lines.
--   2. CREATE OR REPLACE logistics_receive_po_with_do — payload now requires
--      `id` per line element (the line's UUID) instead of scoping by sku
--      alone. Direct id lookup means no ambiguity even when same-SKU
--      multi-variant lines exist.
--
-- COALESCE choice: jsonb's stable canonical text representation makes
-- attrs::text deterministic for semantic equality (key order is canonicalized
-- on insert). NULL attrs collapses to '' so two NULL-attrs rows with the
-- same (po_id, sku) still conflict — preserves the original constraint for
-- mattress lines (which have no attrs).
--
-- Backward compat: existing rows have attrs IS NULL. After this migration:
--   - Mattress lines (NULL attrs) still uniquely scoped by (po_id, sku).
--   - Bedframe + sofa lines now allowed to coexist with same SKU when attrs
--     differs.
--   - Old ReceivePOModal payload (sku only) WILL FAIL — see api/web update
--     in this PR. Tests are also updated in lockstep.
--
-- CLAUDE.md §14 #6 satisfied: 0017/0019/0024/0038b/0053/0073 stay
-- byte-identical; 0076 is the only new migration. Loo gave explicit
-- in-conversation approval per §7 + §14 #1 on 2026-05-10.
-- =============================================================================


-- ----------------------------------------------------------------------------
-- 1. Replace primary key with synthetic UUID column.
-- ----------------------------------------------------------------------------
alter table public.purchase_order_lines
  drop constraint purchase_order_lines_pkey;

alter table public.purchase_order_lines
  add column id uuid not null default gen_random_uuid();

alter table public.purchase_order_lines
  add primary key (id);


-- ----------------------------------------------------------------------------
-- 2. Unique index on (po_id, sku, attrs::text canonical) — prevents accidental
-- duplicate insertion of the same (po, sku, attrs) tuple while allowing
-- different attrs to coexist freely.
-- ----------------------------------------------------------------------------
create unique index po_lines_sku_attrs_uniq
  on public.purchase_order_lines (po_id, sku, (coalesce(attrs::text, '')));

comment on index public.po_lines_sku_attrs_uniq is
  'Multi-variant guard (Loo 2026-05-10): same (po, sku, attrs) is a duplicate; different attrs (e.g. BF-001 Natural Oak vs Walnut) coexist freely. Mattress lines with NULL attrs collapse to '''' so they remain uniquely scoped by (po_id, sku) as before.';


-- ----------------------------------------------------------------------------
-- 3. logistics_receive_po_with_do — replace 0053:421-640. Payload schema
-- changes: each line element now requires `id` (the line's UUID) for direct
-- lookup. SKU lookup alone is no longer safe because (po_id, sku) is no
-- longer a unique key. Everything else (role gate, DO validation, sup_status
-- branching, thread advancement, stock reservation, audit/history) is
-- byte-for-byte preserved.
--
-- Diff vs 0053:
--   (a) New v_line_id local + parse from v_line->>'id'.
--   (b) SELECT/UPDATE WHERE clauses scope by (id = v_line_id, po_id =
--       p_po_id) — po_id check is defense-in-depth (id is globally unique
--       but a misconfigured client passing wrong id should fail loudly).
--   (c) Error message references id when line not found (operators debug by
--       line UUID now, not sku).
-- ----------------------------------------------------------------------------
create or replace function public.logistics_receive_po_with_do(
  p_po_id        text,
  p_do_file_path text,
  p_do_number    text,
  p_lines        jsonb
)
returns jsonb
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_po                 purchase_orders;
  v_role               app_role;
  v_partner_id         uuid;
  v_actor              text;
  v_line               jsonb;
  v_line_id            uuid;
  v_sku                text;
  v_received_qty       int;
  v_existing_line      purchase_order_lines;
  v_delta              int;
  v_outstanding        int;
  v_lines_updated      int := 0;
  v_threads_advanced   int := 0;
  v_thread             record;
  v_reserve            record;
  v_uid                uuid;
  v_was_relocated      boolean;
  v_target_thread_stage logistics_stage;
  v_target_sup_status  po_sup_status;
begin
  v_role := public.app_role();
  v_partner_id := public.app_partner_id();
  v_uid := (select auth.uid());

  -- Role gate: logistics OR partner.
  if v_role not in ('logistics', 'partner') then
    raise exception 'forbidden: logistics or partner only'
      using errcode = '42501', detail = 'forbidden';
  end if;

  -- Validate inputs.
  if p_do_file_path is null or length(btrim(p_do_file_path)) = 0 then
    raise exception 'DO file path is required' using errcode = '22023', detail = 'do_file_path_required';
  end if;
  if p_do_number is null or length(btrim(p_do_number)) < 3 then
    raise exception 'DO number must be at least 3 characters' using errcode = '22023', detail = 'do_number_too_short';
  end if;
  if p_lines is null or jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) = 0 then
    raise exception 'lines must be a non-empty array' using errcode = '22023', detail = 'lines_empty';
  end if;

  -- Lock PO row.
  select * into v_po from purchase_orders where id = p_po_id for update;
  if not found then
    raise exception 'PO not found' using errcode = '42P01', detail = 'po_not_found';
  end if;

  if v_role = 'partner' then
    if v_partner_id is null or v_po.procurement_partner_id is distinct from v_partner_id then
      raise exception 'forbidden: cross-partner receive' using errcode = '42501', detail = 'forbidden';
    end if;
  end if;

  if v_po.status is distinct from 'open' then
    raise exception 'PO is not open (status=%)', v_po.status using errcode = '22023', detail = 'po_not_open';
  end if;

  -- v3 BRANCH: detect Sofa Reject + Relocate path.
  v_was_relocated := (v_po.sup_status = 'relocated');

  v_actor := coalesce((select name from app_users where id = v_uid), initcap(v_role::text));

  -- 0076: per-line update now keys by `id` (the line UUID) since (po_id, sku)
  -- is no longer unique once same-sku-different-attrs lines coexist.
  for v_line in select * from jsonb_array_elements(p_lines) loop
    v_line_id := nullif(v_line->>'id', '')::uuid;
    v_received_qty := nullif(v_line->>'received_qty', '')::int;

    if v_line_id is null or v_received_qty is null or v_received_qty < 0 then
      raise exception 'invalid line: id=%, received_qty=%', v_line_id, v_received_qty
        using errcode = '22023', detail = 'invalid_line';
    end if;

    select * into v_existing_line from purchase_order_lines
     where id = v_line_id and po_id = p_po_id for update;
    if not found then
      raise exception 'PO line not found for id=%', v_line_id using errcode = '42P01', detail = 'po_line_not_found';
    end if;

    v_sku := v_existing_line.sku;

    if v_received_qty > v_existing_line.qty then
      raise exception 'over-received: % > ordered %', v_received_qty, v_existing_line.qty
        using errcode = 'P0001', detail = 'over_received';
    end if;

    v_delta := v_received_qty - v_existing_line.received_qty;
    if v_delta < 0 then
      raise exception 'received_qty must be >= currently received (%)', v_existing_line.received_qty
        using errcode = 'P0001', detail = 'received_qty_decrease';
    end if;

    update purchase_order_lines set received_qty = v_received_qty
     where id = v_line_id;

    if v_delta > 0 then
      insert into stock_balances (sku, warehouse_id, qty)
        values (v_sku, v_po.warehouse_id, v_delta)
        on conflict (sku, warehouse_id)
        do update set qty = stock_balances.qty + v_delta, updated_at = now();

      insert into stock_movements (sku, warehouse_id, qty, kind, ref, by_role, by_user_id)
      values (v_sku, v_po.warehouse_id, v_delta, 'in', p_po_id, v_role, v_uid);

      v_lines_updated := v_lines_updated + 1;
    end if;
  end loop;

  -- Advance threads + reserve. v3 BRANCH on v_was_relocated:
  for v_thread in
    select * from order_supplier_threads
     where po_id = p_po_id and logistics_stage = 'awaiting_logistics_action'
  loop
    -- Determine target thread stage per branch.
    if v_was_relocated then
      v_target_thread_stage := 'waiting';  -- Sofa Reject path
    else
      v_target_thread_stage := case when v_thread.sop_name = 'SOFA_SPECIAL'
                                    then 'dispatched'
                                    else 'ready_to_dispatch'
                               end;
    end if;

    update order_supplier_threads
       set logistics_stage = v_target_thread_stage,
           warehouse_id    = v_po.warehouse_id,
           reserved_at     = now(),
           updated_at      = now()
     where id = v_thread.id;

    v_threads_advanced := v_threads_advanced + 1;

    -- Reserve stock for thread's slice (unchanged from 0034:893-927).
    for v_reserve in
      select ol.sku as sku, ol.qty as qty
        from order_lines ol
        join product_skus ps on ps.sku = ol.sku
        join product_models pm on pm.id = ps.model_id
       where ol.order_id = v_thread.order_id
         and ps.supplier_id = v_thread.supplier_id
         and pm.category::text = v_thread.category
    loop
      begin
        update stock_balances
           set reserved   = reserved + v_reserve.qty, updated_at = now()
         where sku = v_reserve.sku and warehouse_id = v_po.warehouse_id;
        if not found then
          raise exception 'no stock_balances row for sku=% wh=%', v_reserve.sku, v_po.warehouse_id
            using errcode = 'P0001', detail = 'insufficient_stock_for_reserve';
        end if;
      exception
        when check_violation then
          raise exception 'cannot reserve sku=% at wh=% (qty < reserved + %)',
                          v_reserve.sku, v_po.warehouse_id, v_reserve.qty
            using errcode = 'P0001', detail = 'insufficient_stock_for_reserve';
      end;
    end loop;
  end loop;

  -- Determine target PO sup_status per branch.
  select count(*) into v_outstanding
    from purchase_order_lines where po_id = p_po_id and received_qty < qty;

  if v_outstanding = 0 then
    -- Full receive. Branch on relocated flag.
    if v_was_relocated then
      v_target_sup_status := 'at_warehouse_waiting';  -- Codex F3: new value from 0043
    else
      v_target_sup_status := 'delivered';  -- Codex F3: existing valid value (0034:938)
    end if;

    update purchase_orders
       set status         = 'received',
           sup_status     = v_target_sup_status,
           do_file_path   = p_do_file_path,
           do_uploaded_at = now(),
           do_uploaded_by = v_uid,
           updated_at     = now()
     where id = p_po_id;
  else
    -- Partial receive: persist DO + sup_status remains current.
    update purchase_orders
       set do_file_path   = p_do_file_path,
           do_uploaded_at = now(),
           do_uploaded_by = v_uid,
           updated_at     = now()
     where id = p_po_id;
  end if;

  -- Audit + history.
  insert into po_history (po_id, text, by_role)
  values (p_po_id,
          format('Received with DO %s (%s path) — %s line(s), %s thread(s)',
                 btrim(p_do_number),
                 case when v_was_relocated then 'relocated→at_warehouse_waiting' else 'normal→delivered' end,
                 v_lines_updated, v_threads_advanced),
          v_role);

  insert into audit_log (role, actor_text, action, ref)
  values (v_role, v_actor,
          format('Received PO %s with DO %s', p_po_id, btrim(p_do_number)), p_po_id);

  return jsonb_build_object(
    'po_id',             p_po_id,
    'do_file_path',      p_do_file_path,
    'do_number',         btrim(p_do_number),
    'lines_updated',     v_lines_updated,
    'threads_advanced',  v_threads_advanced,
    'po_status',         (select status from purchase_orders where id = p_po_id),
    'sup_status',        (select sup_status from purchase_orders where id = p_po_id),
    'was_relocated',     v_was_relocated
  );
end;
$$;

revoke all on function public.logistics_receive_po_with_do(text, text, text, jsonb) from public;
revoke all on function public.logistics_receive_po_with_do(text, text, text, jsonb) from anon;
grant execute on function public.logistics_receive_po_with_do(text, text, text, jsonb) to authenticated;
