-- =============================================================================
-- 0372_a_lineage_you_cannot_order_is_not_a_lineage.sql
-- WAREHOUSE UNIT AUTHORITY — the physical lineage could not be put in order.
--
-- FOUND BY REVIEW, 2026-08-20, the first time anyone actually READ a lineage
-- rather than asserting the trigger fired.
--
-- Driving one Unit through a governed life in a single transaction — born,
-- bound to an order, flagged for repair, handed to a carrier, verified, its
-- ownership corrected, its condition regraded — wrote all eight events
-- correctly and then returned them in this order:
--
--     status_changed -> unit_born -> reservation_changed -> condition_changed
--     -> protection_changed -> verified -> holder_changed -> ownership_changed
--
-- A Unit that was BORN second. The events are right; the sequence is not
-- recoverable. `event_at` defaults to `now()`, which in Postgres is the
-- TRANSACTION start time, so every event written inside one transaction shares
-- a timestamp to the microsecond and `order by event_at` degenerates to
-- whatever the uuid tiebreak happens to give.
--
-- That is not cosmetic. Stock MASTER §7 asks In & out to show "actual time,
-- Unit, event, From, To, handled by, source and evidence", and §6 requires a
-- correction to preserve "the original event, corrected fact, reason, evidence,
-- actor, time". An append-only history whose order cannot be reconstructed
-- answers none of those questions — and every governed door writes several
-- events in one transaction, so this is the NORMAL case, not an edge.
--
-- TWO FIXES, because either alone still leaves a tie:
--   · `event_at` now defaults to `clock_timestamp()` — the real moment the
--     statement ran, not the moment the transaction opened.
--   · a monotonic `seq` breaks any remaining tie for good. Two events CAN share
--     a clock reading; nothing can share a sequence value. `order by seq` is
--     the total order, and it is the one readers should use.
--
-- Existing rows keep their timestamps and receive sequence values in insertion
-- order. There are none on production today (0 rows), so this rewrites nothing.
--
-- Asserts NO production row count.
-- =============================================================================

set search_path = public;

-- ─── 1 · A real clock, and a total order ────────────────────────────────────
alter table public.stock_unit_events
  alter column event_at set default clock_timestamp();

alter table public.stock_unit_events
  add column if not exists seq bigint generated by default as identity;

-- Existing rows (none today) get sequence values in insertion order, so the
-- column is a total order over the whole table from the moment it exists.
update public.stock_unit_events set seq = seq where seq is null;

alter table public.stock_unit_events
  alter column seq set not null;

create unique index if not exists stock_unit_events_seq_uq
  on public.stock_unit_events (seq);

-- The index readers actually use: one Unit's life, in order.
drop index if exists stock_unit_events_unit_idx;
create index if not exists stock_unit_events_unit_seq_idx
  on public.stock_unit_events (unit_id, seq);

comment on column public.stock_unit_events.seq is
  '0372 — THE order of a Unit''s life. `event_at` alone cannot order events '
  'written in one transaction, and every governed door writes several. Read '
  '`order by seq`, never `order by event_at`.';
comment on column public.stock_unit_events.event_at is
  '0372 — clock_timestamp(): the moment the statement ran. `now()` is the '
  'TRANSACTION start time and tied every event in a transaction together.';

-- ─── 2 · The append-only guard covers the new column too ────────────────────
-- (`trg_stock_unit_events_append_only` refuses every UPDATE and DELETE
-- outright, so `seq` is as immutable as the rest of the row. Asserted below.)

-- ─── 3 · SANITY — schema only.
--      The BEHAVIOUR (a Unit driven through several events in one transaction,
--      ordered correctly, with the sequence refused to any rewrite) is proven
--      against production in a rolled-back transaction and recorded in
--      docs/stock/MASTER.md. A migration that raises and catches its own
--      exception to undo its own probe is clever, fragile and hard to read;
--      the probe belongs outside it.
-- ─────────────────────────────────────────────────────────────────────────────

do $$
begin
  if not exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'stock_unit_events'
       and column_name = 'seq' and is_nullable = 'NO'
  ) then
    raise exception '0372 sanity: the lineage has no compulsory sequence';
  end if;

  if not exists (
    select 1 from pg_indexes
     where schemaname = 'public' and indexname = 'stock_unit_events_seq_uq'
  ) then
    raise exception '0372 sanity: the sequence is not unique, so it is not an order';
  end if;

  if not exists (
    select 1 from pg_indexes
     where schemaname = 'public' and indexname = 'stock_unit_events_unit_seq_idx'
  ) then
    raise exception '0372 sanity: one unit''s life has no ordered index';
  end if;

  -- The default must be the real clock, not the transaction's start.
  if coalesce((
    select column_default from information_schema.columns
     where table_schema = 'public' and table_name = 'stock_unit_events'
       and column_name = 'event_at'), '') not like '%clock_timestamp%' then
    raise exception '0372 sanity: event_at still defaults to the transaction clock';
  end if;

  -- The append-only guard still stands over the whole row.
  if not exists (
    select 1 from pg_trigger
     where tgrelid = 'public.stock_unit_events'::regclass
       and tgname = 'stock_unit_events_append_only'
       and not tgisinternal
  ) then
    raise exception '0372 sanity: the lineage lost its append-only guard';
  end if;

  raise notice '0372 OK: the lineage has a total order and keeps its guard';
end $$;
