-- 0492 · The loan offer is a record on the Sales Order
-- 【DELIVERY】 CARD 15 · Loan offer record and Delivery connection
-- (Delivery MASTER §14.2 · Orders MASTER §7 / Card 6)
--
-- Loan is conditional: it appears only when a real stock delay and a customer
-- decision create the need. Carres Operation OFFERS the loan and records the
-- customer's answer on the Sales Order; the offer, the acceptance or the
-- decline is a record in Orders beside `ops_sofa_loans` (the loan itself, 0209).
-- Logistics never makes the commercial offer. A loan never blocks a Delivery
-- Order. Order Route holds the whole history; Monitor prints only the current
-- loan line; the `Collect the loan item` Work reads `ops_sofa_loans` as before.
--
-- Append-only: an offer is never edited; a later record supersedes it.

set search_path = public;

create table if not exists public.ops_loan_offers (
  id uuid primary key default gen_random_uuid(),
  -- The append order. Two records written in one transaction share `now()`,
  -- so the LATEST is decided by this sequence, never by a timestamp tie.
  seq bigint generated by default as identity,
  order_id uuid not null references public.orders(id) on delete restrict,
  event text not null check (event in ('offered', 'accepted', 'declined')),
  -- The exact Unit offered, when Operation names one (a display piece, a
  -- free own-stock Unit). A supplier borrow names none.
  item_id uuid references public.ops_stock_items(id) on delete restrict,
  -- What was offered, in the operator's words: `Display sofa · HK55-3S`.
  label text,
  -- Why it was offered (the stock delay), or why the customer declined.
  reason text,
  recorded_by uuid references public.app_users(id),
  recorded_at timestamptz not null default now(),
  constraint ops_loan_offers_offer_says_what check (event <> 'offered' or (label is not null and btrim(label) <> '')),
  constraint ops_loan_offers_decline_says_why check (event <> 'declined' or (reason is not null and btrim(reason) <> ''))
);
create index if not exists ops_loan_offers_order_idx on public.ops_loan_offers (order_id, seq desc);
comment on table public.ops_loan_offers is
  '0492: the loan OFFER and the customer''s answer, recorded on the Sales Order beside ops_sofa_loans (Delivery MASTER §14.2). Append-only; the latest record is the current state; the loan itself is still the 0209 row.';

alter table public.ops_loan_offers enable row level security;
revoke all on public.ops_loan_offers from public, anon, authenticated;
grant select on public.ops_loan_offers to authenticated;
drop policy if exists ops_loan_offers_read on public.ops_loan_offers;
create policy ops_loan_offers_read on public.ops_loan_offers
  for select using ((select public.is_internal()));

create or replace function public.ops_loan_offers_no_rewrite()
returns trigger language plpgsql as $$
begin
  raise exception 'a loan offer is history — a later record supersedes it, nothing edits it'
    using errcode = 'P0001', detail = 'loan_offer_append_only';
end $$;
drop trigger if exists ops_loan_offers_no_rewrite on public.ops_loan_offers;
create trigger ops_loan_offers_no_rewrite
  before update or delete on public.ops_loan_offers
  for each row execute function public.ops_loan_offers_no_rewrite();

-- ── The one door ─────────────────────────────────────────────────────────────
create or replace function public.sales_order_loan_offer_record(
  p_order_id uuid, p_event text, p_item_id uuid, p_label text, p_reason text
) returns jsonb
language plpgsql security definer
set search_path = public, pg_temp
as $fn$
declare
  v_order orders;
  v_latest ops_loan_offers;
  v_row ops_loan_offers;
  v_label text := nullif(btrim(coalesce(p_label, '')), '');
  v_reason text := nullif(btrim(coalesce(p_reason, '')), '');
begin
  if not (select public.is_operation()) then
    raise exception 'Only operation or principal may record a loan offer' using errcode = '42501';
  end if;
  if p_event not in ('offered', 'accepted', 'declined') then
    raise exception 'a loan record is offered, accepted or declined' using errcode = '22023', detail = 'bad_event';
  end if;
  select * into v_order from orders where id = p_order_id for update;
  if not found then
    raise exception 'order not found' using errcode = 'P0002';
  end if;
  select * into v_latest from ops_loan_offers where order_id = p_order_id order by seq desc limit 1;
  if p_event = 'offered' then
    if v_label is null then
      raise exception 'say what is offered' using errcode = '22023', detail = 'label_required';
    end if;
    if p_item_id is not null and not exists (select 1 from ops_stock_items where id = p_item_id and qty = 1) then
      raise exception 'the offered Unit must be an exact Unit' using errcode = '22023', detail = 'unit_required';
    end if;
  else
    -- An answer answers an OFFER that is still open: the latest record must be the offer.
    if v_latest.id is null or v_latest.event <> 'offered' then
      raise exception 'record the offer before the customer''s answer' using errcode = '22023', detail = 'no_open_offer';
    end if;
    if p_event = 'declined' and v_reason is null then
      raise exception 'say why the customer declined' using errcode = '22023', detail = 'reason_required';
    end if;
  end if;
  insert into ops_loan_offers (order_id, event, item_id, label, reason, recorded_by)
  values (p_order_id, p_event,
          case when p_event = 'offered' then p_item_id else v_latest.item_id end,
          case when p_event = 'offered' then v_label else v_latest.label end,
          v_reason, auth.uid())
  returning * into v_row;
  insert into order_history (order_id, text, by_role)
  values (p_order_id,
          case p_event
            when 'offered' then format('Loan offered · %s%s', v_row.label, case when v_reason is not null then ' — ' || v_reason else '' end)
            when 'accepted' then format('Customer accepted the loan · %s', v_row.label)
            else format('Customer declined the loan · %s — %s', v_row.label, v_reason) end,
          (select public.app_role()));
  return to_jsonb(v_row);
end;
$fn$;
revoke all on function public.sales_order_loan_offer_record(uuid, text, uuid, text, text) from public, anon;
grant execute on function public.sales_order_loan_offer_record(uuid, text, uuid, text, text) to authenticated;
