import { supabase } from "./supabase";
import { dataUrlToBlob } from "../pages/dealer/new-order/draft";

/**
 * Browser → Supabase Storage upload helpers, scoped to the `orders-attachments`
 * bucket. Path convention (per Phase 2B.3.a /plan-eng-review D1):
 *
 *     orders-attachments/{dealerId}/{wizardSessionId}/signature.png
 *     orders-attachments/{dealerId}/{wizardSessionId}/payment-slip.{ext}
 *
 * RLS gates the WRITE side: the dealer's JWT carries `dealer_id`, and the
 * Storage policy `(storage.foldername(name))[1] = (select public.app_dealer_id())::text`
 * blocks any cross-dealer upload at the database layer. The API also revalidates
 * the prefix on POST /api/orders before persisting, so a bad path can't bypass
 * the guard via a hand-crafted JSON payload.
 *
 * The functions here return the *path string* (e.g. `orders-attachments/abc/123/signature.png`)
 * — that's what the API stores. Read-side signed URLs are generated by the
 * server in GET /api/orders/:id (1h TTL).
 */

export const ATTACHMENTS_BUCKET = "orders-attachments";

/**
 * Returns a fresh-enough UUID for the wizard session folder. Uses the native
 * crypto.randomUUID where available (Chrome/Edge/Safari/FF current); falls
 * back to a Math.random scheme for ancient browsers (still rare in 2026 but
 * cheap insurance against ReferenceError on first paint).
 */
export function newWizardSessionId(): string {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return crypto.randomUUID();
  }
  // RFC4122 v4-ish fallback. Quality is good enough for a folder name; we
  // never use it as a security boundary.
  const rand = (n: number) => Math.floor(Math.random() * n);
  const hex = (n: number, width: number) => n.toString(16).padStart(width, "0");
  return `${hex(rand(0xffffffff), 8)}-${hex(rand(0xffff), 4)}-${hex(0x4000 | rand(0xfff), 4)}-${hex(
    0x8000 | rand(0x3fff),
    4,
  )}-${hex(rand(0xffffffff), 8)}${hex(rand(0xffff), 4)}`;
}

interface BaseUploadArgs {
  dealerId: string;
  wizardSessionId: string;
  /** Filename within the wizard folder (e.g. "signature.png"). */
  filename: string;
}

interface BlobUploadArgs extends BaseUploadArgs {
  blob: Blob;
}

interface DataUrlUploadArgs extends BaseUploadArgs {
  dataUrl: string;
}

/**
 * Filename extension → safe Content-Type. We *never* trust the client-supplied
 * blob.type when uploading: a tampered sessionStorage draft could carry
 * `mime: "text/html"` with an HTML+JS body, and Supabase Storage would serve
 * it back with that attacker-chosen Content-Type when an internal viewer
 * (Phase 2C+) opens the signed URL — classic stored XSS in the
 * storage.supabase.co context. Whitelisting from the filename extension
 * cuts that path cleanly: the dealer can swap the bytes but not the
 * Content-Type Supabase serves.
 */
const SAFE_CONTENT_TYPE_BY_EXT: Record<string, string> = {
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  heic: "image/heic",
  heif: "image/heif",
  pdf: "application/pdf",
};

function contentTypeFromFilename(filename: string): string {
  const dot = filename.lastIndexOf(".");
  const ext = dot >= 0 ? filename.slice(dot + 1).toLowerCase() : "";
  const mime = SAFE_CONTENT_TYPE_BY_EXT[ext];
  if (!mime) {
    throw new Error(
      `Unsupported attachment extension: .${ext || "(none)"} — only png/jpg/heic/pdf allowed`,
    );
  }
  return mime;
}

/**
 * Uploads a single Blob to the orders-attachments bucket. Returns the full
 * Storage path (including the bucket prefix) — that's what the API expects.
 * Throws on RLS denial / network failure / bucket-not-found.
 *
 * Content-Type is derived from the filename extension via
 * `contentTypeFromFilename` — never from `blob.type` — so a tampered draft
 * cannot trick Supabase into serving the file back with a hostile MIME.
 */
export async function uploadAttachment({
  dealerId,
  wizardSessionId,
  filename,
  blob,
}: BlobUploadArgs): Promise<string> {
  const safeContentType = contentTypeFromFilename(filename);
  const objectKey = `${dealerId}/${wizardSessionId}/${filename}`;
  const { error } = await supabase.storage
    .from(ATTACHMENTS_BUCKET)
    .upload(objectKey, blob, {
      // Re-uploading the same logical file (e.g. dealer redrew the signature)
      // should overwrite; otherwise the first attempt's stale path wins.
      upsert: true,
      contentType: safeContentType,
    });
  if (error) {
    throw new Error(`Upload failed (${filename}): ${error.message}`);
  }
  return `${ATTACHMENTS_BUCKET}/${objectKey}`;
}

/** Convenience wrapper — turns a base64 dataURL into a Blob and uploads it. */
export async function uploadDataUrl(args: DataUrlUploadArgs): Promise<string> {
  const blob = dataUrlToBlob(args.dataUrl);
  return uploadAttachment({
    dealerId: args.dealerId,
    wizardSessionId: args.wizardSessionId,
    filename: args.filename,
    blob,
  });
}

/** Mime → file extension for slip uploads. */
export function extensionForMime(mime: string): string {
  if (mime === "image/jpeg") return "jpg";
  if (mime === "image/png") return "png";
  if (mime === "image/heic" || mime === "image/heif") return "heic";
  if (mime === "application/pdf") return "pdf";
  return "bin";
}
